# Generated by Django 4.1.1 on 2022-10-04 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidade', '0001_initial'),
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_contrato', models.IntegerField()),
                ('num_os', models.IntegerField()),
                ('node', models.CharField(max_length=64)),
                ('mac_adress', models.CharField(max_length=128)),
                ('modelo_equipamento', models.CharField(max_length=128)),
                ('reclamacao_cliente', models.TextField()),
                ('observacao', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidade.area')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidade.cidade')),
                ('cod_cancelamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.codcancelamento')),
                ('descricao_problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.descricaoproblema')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidade.estado')),
                ('grupo_problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.grupoproblema')),
                ('tipo_contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.tipocontato')),
                ('tipo_os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.tipoos')),
                ('tipo_solucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.tiposolucao')),
            ],
        ),
    ]
