# Generated by Django 4.1.1 on 2022-10-03 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodCancelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cancelamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_problema', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contato', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_os', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solucao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DescricaoProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_problema', models.CharField(max_length=100)),
                ('grupo_problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.grupoproblema')),
            ],
        ),
    ]
